<?php
/*
*Form Alta de revisión
*@author: mvasquez & varteaga
*@date: 29/09/2015
*/

function alta_menu() {
  $items['Alta'] = array(
    'title' => 'Alta de nueva revisión.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alta_form'),
    'access callback' => TRUE,
    'weight' => 9,
    'menu_name' => 'main-menu',
    'options' => array('attributes' => array('class' => 'menu_alta')),
    );
  return $items;
}

function alta_permission() {
  return array(
    'Alta/' => array(
      'title' => t('Permisos para ingresar al formulario de alta de revisiones'),
      'description' => t('Seleccion de usuarios que pueden tener acceso.'),
    ),
  );
}

function alta_form($form, &$form_submit) {
	
  if (empty($form_submit['storage'])) {
    $form_submit['storage'] = array(
      'step' => 'alta_rev_form',
    );
  }
  $function = $form_submit['storage']['step'];
  $form = $function($form, $form_submit);
  return $form;
}


function alta_rev_form($form,&$form_submit) {
	
	$form['#attached']['css'] = array(
	drupal_get_path('module','Alta') . '/Alta.css'
	);
	
	$nom_org='';
	$tipo_org='';
	$fecha_sol='';
	$fecha_disp='';
	$fecha_ini='';
	$fecha_fin='';
	$nom_adm='';
	$correo_adm='';
	$tel_adm='';
	$nom_tec='';
	$correo_tec='';
	$tel_tec='';
	$sist_op='';
	$sist_op_ver='';
	$ip_sitio='';
	$prot_acc_rem='';
	$puer_acc_rem='';
	$dir_usua='';
	$ip_web='';
	$puer_acc_web='';
	$url_sitio='';
	$soft_web='';
	$ver_web='';
	$ip_bd='';
	$puer_acc_bd='';
	$nom_bd='';
	$soft_bd='';
	$ver_bd='';
	
  $mensaje = "<div>Captura los datos que se encuentran en la solicitud de revisión.<d/iv><div class='categoria'><br>INFORMACION GENERAL</div>";  
  $form['inicio'] = array(
    '#type' => 'item',
    '#title' => $mensaje,
  );
 
  $info1 = "<div class='apartado'><u>Organización.</u></div>";  
  $form['info1'] = array(
    '#type' => 'item',
    '#title' => $info1,
  );
  
  $form['nom_org'] = array(
    '#title' => t('Nombre de la organización:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $nom_org,
    '#filters' => array('trim','strip_tags'),
  );
  $form['tipo_org'] = array(
    '#title' => t('Tipo de organización:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $tipo_org,
    '#filters' => array('trim','strip_tags'),
  );
  
  $info2 = "<div class='apartado'><u>Periodo de revisión.</u></div>";  
  $form['info2'] = array(
    '#type' => 'item',
    '#title' => $info2,
  );
  
  $form['fecha_sol'] = array(
    '#title' => t('Fecha de solicitud:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('aaaa-mm-dd'),
    '#default_value' => $fecha_sol,
    '#filters' => array('trim','strip_tags'),
  );
  
   $form['fecha_disp'] = array(
    '#title' => t('Fecha de disponibilidad de la CSI/UNAM-CERT'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('aaaa-mm-dd'),
    '#default_value' => $fecha_disp,
    '#filters' => array('trim','strip_tags'),
  );
  
   $form['fecha_ini'] = array(
    '#title' => t('Fecha de inicio de la revisión:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('aaaa-mm-dd'),
    '#default_value' => $fecha_ini,
    '#filters' => array('trim','strip_tags'),
  );
  
   $form['fecha_fin'] = array(
    '#title' => t('Fecha de fin de la revisión:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('aaaa-mm-dd'),
    '#default_value' => $fecha_fin,
    '#filters' => array('trim','strip_tags'),
  );

  $info3 = "<div class='categoria'>DATOS DE CONTACTO</div>";  
  $form['info3'] = array(
    '#type' => 'item',
    '#title' => $info3,
  );
  
  $info4 = "<div class='apartado'><u>Contacto administrativo -Administrador del proyecto.</u></div>";  
  $form['info4'] = array(
    '#type' => 'item',
    '#title' => $info4,
  );
  
  $form['nom_con_adm'] = array(
    '#title' => t('Nombre completo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $nom_adm,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['correo_con_adm'] = array(
    '#title' => t('Correo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $correo_adm,
  );
  
  $form['tel_con_adm'] = array(
    '#title' => t('Teléfono'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $tel_adm,
  );
  
   $info5 = "<div class='apartado'><u>Contacto técnico -Administrador del sitio web.</u></div>";  
   $form['info5'] = array(
    '#type' => 'item',
    '#title' => $info5,
  );
  
   $form['nom_con_tec'] = array(
    '#title' => t('Nombre completo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $nom_tec,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['correo_con_tec'] = array(
    '#title' => t('Correo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $correo_tec,
  );
  
  $form['tel_con_tec'] = array(
    '#title' => t('Teléfono'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $tel_tec,
    '#filters' => array('trim','strip_tags'),
  );
  
  $info6 = "<div class='categoria'>REQUERIMIENTOS</div>";  
  $form['info6'] = array(
    '#type' => 'item',
    '#title' => $info6,
  );
    $info7 = "<div class='apartado'><u>Sistema Operativo</u></div>";  
   $form['info7'] = array(
    '#type' => 'item',
    '#title' => $info7,
  );
  
  
  $form['sist_op'] = array(
    '#title' => t('Sistema Operativo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $sist_op,
    '#filters' => array('trim','strip_tags'),
  );
  
  
  $form['sist_op_ver'] = array(
    '#title' => t('Version Sistema Operativo:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $sist_op_ver,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['ip_sitio'] = array(
    '#title' => t('Direccion(es) IP:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $ip_sitio,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['prot_acc_rem'] = array(
    '#title' => t('Protocolo de acceso remoto:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $prot_acc_rem,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['puer_acc_rem'] = array(
    '#title' => t('Puerto de acceso remoto'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $puer_acc_rem,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['dir_usua'] = array(
    '#title' => t('Directorio del usuario'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $dir_usua,
    '#filters' => array('trim','strip_tags'),
  );
  
   $info8 = "<div class='apartado'><u>Sitio web</u></div>";  
   $form['info8'] = array(
    '#type' => 'item',
    '#title' => $info8,
  );
  
  $form['ip_web'] = array(
    '#title' => t('Direccion(es) IP del servicio web:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $ip_web,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['puer_acc_web'] = array(
    '#title' => t('Puerto(s):'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $puer_acc_web,
    '#filters' => array('trim','strip_tags'),
  );
  
    $form['url_sitio'] = array(
    '#title' => t('URL de las aplicaciones web:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $url_sitio,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['soft_web'] = array(
    '#title' => t('Sofware del servidor web:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $soft_web,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['ver_web'] = array(
    '#title' => t('Versión del servidor web:'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => $ver_web,
    '#filters' => array('trim','strip_tags'),
  );
  
   $info9 = "<div class='apartado'><u>Manejador de Base de Datos</u></div>";  
   $form['info9'] = array(
    '#type' => 'item',
    '#title' => $info9,
  );
  
    $form['ip_bd'] = array(
    '#title' => t('Direccion(es) IP:'),
    '#type' => 'textfield',
    '#required' => FALSE,
    '#default_value' => $ip_bd,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['puer_acc_bd'] = array(
    '#title' => t('Puerto(s):'),
    '#type' => 'textfield',
    '#required' => FALSE,
    '#default_value' => $puer_acc_bd,
    '#filters' => array('trim','strip_tags'),
  );
  
    $form['nom_bd'] = array(
    '#title' => t('Nombre de la base de datos:'),
    '#type' => 'textfield',
    '#required' => FALSE,
    '#default_value' => $nom_bd,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['soft_bd'] = array(
    '#title' => t('Sofware del servidor de base de datos:'),
    '#type' => 'textfield',
    '#required' => FALSE,
    '#default_value' => $soft_bd,
    '#filters' => array('trim','strip_tags'),
  );
  
  $form['ver_bd'] = array(
    '#title' => t('Versión del servidor de base de datos:'),
    '#type' => 'textfield',
    '#required' => FALSE,
    '#default_value' => $ver_bd,
    '#filters' => array('trim','strip_tags'),
  );
  
	$form['submit'] = array(
      '#value' => 'Subir',
      '#type' => 'submit',
      '#submit' => array('alta_rev_enviar'),
    );	
  
  $form['#validate'][] = 'alta_rev_validar';
  return $form; 
}

//Validacion
function alta_rev_validar($form, &$form_submit){
	//FILTER_SANATIZE_STRING -> Quita etiquetas y elimina o codifica los caracteres especiales de una cadena.
	//strip_tags -> Retira las etiquetas HTML y PHP de un string.
  	$nom_org=filter_var(strip_tags($form_submit['values']['nom_org']),FILTER_SANITIZE_STRING);
    $tipo_org=filter_var(strip_tags($form_submit['values']['tipo_org']),FILTER_SANITIZE_STRING);
	$fecha_sol=filter_var(strip_tags($form_submit['values']['fecha_sol']),FILTER_SANITIZE_STRING);
	$fecha_disp=filter_var(strip_tags($form_submit['values']['fecha_disp']),FILTER_SANITIZE_STRING);
	$fecha_ini=filter_var(strip_tags($form_submit['values']['fecha_ini']),FILTER_SANITIZE_STRING);
	$fecha_fin=filter_var(strip_tags($form_submit['values']['fecha_fin']),FILTER_SANITIZE_STRING);
	$nom_adm=filter_var(strip_tags($form_submit['values']['nom_con_adm']),FILTER_SANITIZE_STRING);
	$correo_adm=filter_var(strip_tags($form_submit['values']['correo_con_adm']),FILTER_SANITIZE_STRING);
	$tel_adm=filter_var(strip_tags($form_submit['values']['tel_con_adm']));
	$nom_tec=filter_var(strip_tags($form_submit['values']['nom_con_tec']),FILTER_SANITIZE_STRING);
	$correo_tec=filter_var(strip_tags($form_submit['values']['correo_con_tec']),FILTER_SANITIZE_STRING);
	$tel_tec=filter_var(strip_tags($form_submit['values']['tel_con_tec']));
	$sist_op=filter_var(strip_tags($form_submit['values']['sist_op']),FILTER_SANITIZE_STRING);
	$sist_op_ver=filter_var(strip_tags($form_submit['values']['sist_op_ver']),FILTER_SANITIZE_STRING);
	$ip_sitio=filter_var(strip_tags($form_submit['values']['ip_sitio']),FILTER_SANITIZE_STRING);
	$prot_acc_rem=filter_var(strip_tags($form_submit['values']['prot_acc_rem']),FILTER_SANITIZE_STRING);
	$puer_acc_rem=filter_var(strip_tags($form_submit['values']['puer_acc_rem']),FILTER_SANITIZE_STRING);
	$dir_usua=filter_var(strip_tags($form_submit['values']['dir_usua']),FILTER_SANITIZE_STRING);
	$ip_web=filter_var(strip_tags($form_submit['values']['ip_web']),FILTER_SANITIZE_STRING);
	$puer_acc_web=filter_var(strip_tags($form_submit['values']['puer_acc_web']),FILTER_SANITIZE_STRING);
	$url_sitio=filter_var(strip_tags($form_submit['values']['url_sitio']),FILTER_SANITIZE_STRING);
	$soft_web=filter_var(strip_tags($form_submit['values']['soft_web']),FILTER_SANITIZE_STRING);
	$ver_web=filter_var(strip_tags($form_submit['values']['ver_web']),FILTER_SANITIZE_STRING);
	$ip_bd=filter_var(strip_tags($form_submit['values']['ip_bd']),FILTER_SANITIZE_STRING);
	$puer_acc_bd=filter_var(strip_tags($form_submit['values']['puer_acc_bd']),FILTER_SANITIZE_STRING);
	$nom_bd=filter_var(strip_tags($form_submit['values']['nom_bd']),FILTER_SANITIZE_STRING);
	$soft_bd=filter_var(strip_tags($form_submit['values']['soft_bd']),FILTER_SANITIZE_STRING);
	$ver_bd=filter_var(strip_tags($form_submit['values']['ver_bd']),FILTER_SANITIZE_STRING);
 


if(!preg_match('/^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\.\- ]+/',$nom_org)){
	form_set_error('nom_org',t('Ingresar un nombre de organización válido'));
}

if(!preg_match('/^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\.\- ]+/',$tipo_org)){
	form_set_error('tipo_org',t('Ingresar un tipo de organización válido'));
}

if(!preg_match('/^(19|20)\d\d\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$/',$fecha_sol)){
	form_set_error('fecha_sol',t('Ingresar una fecha de solictud válida'));
}

if(!preg_match('/^(19|20)\d\d\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$/',$fecha_disp)){
	form_set_error('fecha_disp',t('Ingresar una fecha de disponibilidad válida'));
}

if(!preg_match('/^(19|20)\d\d\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$/',$fecha_ini)){
	form_set_error('fecha_ini',t('Ingresar una fecha de inicio válida'));
}

if(!preg_match('/^(19|20)\d\d\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$/',$fecha_fin)){
	form_set_error('fecha_fin',t('Ingresar una fecha de fin válida'));
}

if(!preg_match('/^[A-ZÁÉÍÓÚÜÑa-záéíóúüñ][a-záéíóúüñ]+(\s[A-ZÁÉÍÓÚÜÑ]?[a-záéíóúüñ]+)*$/',$nom_adm)){
	form_set_error('nom_adm',t('Ingresar un nombre de contacto administrativo válido'));
}

if(!preg_match('/^[a-zA-Z][a-zA-Z0-9_\-]?(\.?[a-zA-Z0-9_\-])+@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$/',$correo_adm)){
	form_set_error('correo_adm',t('Ingresar un correo de contacto administrativo válido'));
}

if(!preg_match('/^((044\ ?)?[0-9]{8,10})$/',$tel_adm)){
	form_set_error('tel_adm',t('Ingresar un teléfono de contacto administrativo válido'));
}

if(!preg_match('/^[A-ZÁÉÍÓÚÜÑa-záéíóúüñ][a-záéíóúüñ]+(\s[A-ZÁÉÍÓÚÜÑ]?[a-záéíóúüñ]+)*$/',$nom_tec)){
	form_set_error('nom_tec',t('Ingresar un nombre de contacto técnico válido'));
}

if(!preg_match('/^[a-zA-Z][a-zA-Z0-9_\-]?(\.?[a-zA-Z0-9_\-])+@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$/',$correo_tec)){
	form_set_error('correo_tec',t('Ingresar un correo de contacto técnico válido'));
}

if(!preg_match('/^(044\ ?)?[0-9]{8,10}$/',$tel_tec)){
	form_set_error('tel_tec',t('Ingresar un teléfono de contacto técnico válido'));
}

if(!preg_match('/^[A-ZÁÉÍÓÚÜÑa-záéíóúüñ\/\.\ ]+/',$sist_op)){
	form_set_error('sist_op',t('Ingresar un sistema operativo válido'));
}

if(!preg_match('/^[A-ZÁÉÍÓÚÜÑa-záéíóúüñ\/\.\ 0-9]+/',$sist_op_ver)){
	form_set_error('sist_op',t('Ingresar una versión de sistema operativo válida'));
}

if(!preg_match('/^(([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.){3}([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$/',$ip_sitio)){
	form_set_error('ip_sitio',t('Ingresar una dirección IP del sitio válida'));
}

if(!preg_match('/^[a-zA-Z][a-zA-Z0-9\- ]+/',$prot_acc_rem)){
	form_set_error('prot_acc_rem',t('Ingresar un protocolo válido'));
}

if(!preg_match('/^([1-9]|\d\d|\d\d\d|\d\d\d\d|[1-5]\d\d\d\d|6[0-4]\d\d\d|65[0-4]\d\d|655[0-2]\d|6553[0-4])/',$puer_acc_rem)){
	form_set_error('puer_acc_rem',t('Ingresar un puerto de acceso válido'));
}

if(!preg_match('/^(\/[A-ZÁÉÍÓÚÜÑa-záéíóúüñ\.\ \/?]+)/',$dir_usua)){
	form_set_error('dir_usua',t('Ingresar un directorio válido'));
}

if(!preg_match('/^(([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.){3}([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$/',$ip_web)){
	form_set_error('ip_web',t('Ingresar un dirección IP del servicio web válida'));
}

if(!preg_match('/^([1-9]|\d\d|\d\d\d|\d\d\d\d|[1-5]\d\d\d\d|6[0-4]\d\d\d|65[0-4]\d\d|655[0-2]\d|6553[0-4])/',$puer_acc_web)){
	form_set_error('puer_acc_web',t('Ingresar un puerto del servicio web válido'));
}

if(!preg_match('/^((https?\:\/\/)?(www\.)?[A-ZÁÉÍÓÚÜÑa-záéíóúüñ0-9\.\_\-\(\)\/?]+)$/',$url_sitio)){
	form_set_error('url_sitio',t('Ingresar una url del servicio web  válida'));
}

if(!preg_match('/^[A-ZÁÉÍÓÚÜÑa-záéíóúüñ0-9\.\_\-\s]+$/',$soft_web)){
	form_set_error('soft_web',t('Ingresar un nombre del servicio web válido'));
}

if(!preg_match('/^\d{1,}(\.\d{1,})*$/',$ver_web)){
	form_set_error('ver_web',t('Ingresar una versión del servicio web válido'));
}

//MANEJADOR DE BASE DE DATOS

//if( is_null($ip_bd) && is_null($puer_acc_bd) && is_null($nom_bd) && is_null($soft_bd) && is_null($ver_bd)){
if( !(empty($ip_bd) && empty($puer_acc_bd) && empty($nom_bd) && empty($soft_bd) && empty($ver_bd))){
	if(!preg_match('/^((([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.){3}([1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$)/',$ip_bd)){
		form_set_error('ip_bd',t('Ingresar una ip de base de datos válida'));
	}

	if(!preg_match('/^([1-9]|\d\d|\d\d\d|\d\d\d\d|[1-5]\d\d\d\d|6[0-4]\d\d\d|65[0-4]\d\d|655[0-2]\d|6553[0-4])/',$puer_acc_bd)){
		form_set_error('puer_acc_bd',t('Ingresar un puerto de base de datos válido'));
	}

	if(!preg_match('/^([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\.\- ]+)/',$nom_bd)){
		form_set_error('nom_bd',t('Ingresar un nombre de base de datos válido'));
	}

	if(!preg_match('/^([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\.\- ]+)/',$soft_bd)){
		form_set_error('soft_bd',t('Ingresar un software de base de datos válido'));
	}

	if(!preg_match('/^(\d{1,}(\.\d{1,})*$)/',$ver_bd)){
		form_set_error('ver_bd',t('Ingresar un numero de versión de base de datos válido'));
	}
}

$form_submit['values']['nom_org']=$nom_org;
$form_submit['values']['tipo_org']=$tipo_org;
$form_submit['values']['fecha_sol']=$fecha_sol;
$form_submit['values']['fecha_disp']=$fecha_disp;
$form_submit['values']['fecha_ini']=$fecha_ini;
$form_submit['values']['fecha_fin']=$fecha_fin;
$form_submit['values']['nom_con_adm']=$nom_adm;
$form_submit['values']['correo_con_adm']=$correo_adm;
$form_submit['values']['tel_con_adm']=$tel_adm;
$form_submit['values']['nom_con_tec']=$nom_tec;
$form_submit['values']['correo_con_tec']=$correo_tec;
$form_submit['values']['tel_con_tec']=$tel_tec;
$form_submit['values']['sist_op']=$sist_op;
$form_submit['values']['sist_op_ver']=$sist_op_ver;
$form_submit['values']['ip_sitio']=$ip_sitio;
$form_submit['values']['prot_acc_rem']=$prot_acc_rem;
$form_submit['values']['puer_acc_rem']=$puer_acc_rem;
$form_submit['values']['dir_usua']=$dir_usua;
$form_submit['values']['ip_web']=$ip_web;
$form_submit['values']['puer_acc_web']=$puer_acc_web;
$form_submit['values']['url_sitio']=$url_sitio;
$form_submit['values']['soft_web']=$soft_web;
$form_submit['values']['ver_web']=$ver_web;
$form_submit['values']['ip_bd']=$ip_bd;
$form_submit['values']['puer_acc_bd']=$puer_acc_bd;
$form_submit['values']['nom_bd']=$nom_bd;
$form_submit['values']['soft_bd']=$soft_bd;
$form_submit['values']['ver_bd']=$ver_bd;


}

//Almacenamiento de datos
function alta_rev_enviar($form, &$form_submit) {
	$form_state['redirect'] = 'home';
    $nom_org=$form_submit['values']['nom_org'];
    $tipo_org=$form_submit['values']['tipo_org'];
	$fecha_sol=$form_submit['values']['fecha_sol'];
	$fecha_disp=$form_submit['values']['fecha_disp'];
	$fecha_ini=$form_submit['values']['fecha_ini'];
	$fecha_fin=$form_submit['values']['fecha_fin'];
	$nom_adm=$form_submit['values']['nom_con_adm'];
	$correo_adm=$form_submit['values']['correo_con_adm'];
	$tel_adm=$form_submit['values']['tel_con_adm'];
	$nom_tec=$form_submit['values']['nom_con_tec'];
	$correo_tec=$form_submit['values']['correo_con_tec'];
	$tel_tec=$form_submit['values']['tel_con_tec'];
	$sist_op=$form_submit['values']['sist_op'];
	$sist_op_ver=$form_submit['values']['sist_op_ver'];
	$ip_sitio=$form_submit['values']['ip_sitio'];
	$prot_acc_rem=$form_submit['values']['prot_acc_rem'];
	$puer_acc_rem=$form_submit['values']['puer_acc_rem'];
	$dir_usua=$form_submit['values']['dir_usua'];
	$ip_web=$form_submit['values']['ip_web'];
	$puer_acc_web=$form_submit['values']['puer_acc_web'];
	$url_sitio=$form_submit['values']['url_sitio'];
	$soft_web=$form_submit['values']['soft_web'];
	$ver_web=$form_submit['values']['ver_web'];
	$ip_bd=$form_submit['values']['ip_bd'];
	$puer_acc_bd=$form_submit['values']['puer_acc_bd'];
	$nom_bd=$form_submit['values']['nom_bd'];
	$soft_bd=$form_submit['values']['soft_bd'];
	$ver_bd=$form_submit['values']['ver_bd'];
  

  	$transaccion = db_transaction();
  	try {
      $asistente = db_insert('solicitud')->fields(array(
        'nom_org' => $nom_org,
		'tipo_org' => $tipo_org,
		'fecha_sol' => $fecha_sol,
		'fecha_disp' => $fecha_disp,
		'fecha_ini' => $fecha_ini,
		'fecha_fin' => $fecha_fin,
		'nom_adm' => $nom_adm,
		'correo_adm' => $correo_adm,
		'tel_adm' => $tel_adm,
		'nom_tec' => $nom_tec,
		'correo_tec' => $correo_tec,
		'tel_tec' => $tel_tec,
		'sist_op' => $sist_op,
		'sist_op_ver' => $sist_op_ver,
		'ip_sitio' => $ip_sitio,
		'prot_acc_rem' => $prot_acc_rem,
		'puer_acc_rem' => $puer_acc_rem,
		'dir_usua' => $dir_usua,
		'ip_web' => $ip_web,
		'puer_acc_web' => $puer_acc_web,
		'url_sitio' => $url_sitio,
		'soft_web' => $soft_web,
		'ver_web' => $ver_web,
		'ip_bd' => $ip_bd,
		'puer_acc_bd' => $puer_acc_bd,
		'nom_bd' => $nom_bd,
		'soft_bd' => $soft_bd,
		'soft_bd' => $ver_bd,  
      ))->execute();
      drupal_set_message(t('Datos personales guardados con éxito.'));
	  drupal_goto('Lista/');
    }
    catch (Exception $e) {
      $transaccion->rollback();	
      drupal_set_message(t('Hubo un problema con tu Alta. Por favor intente más tarde.'));
    }
	
}
