<?php
/*
*Form Estadisticasdo de revisión
*@author: mvasquez & varteaga
*@date: 29/09/2015
*/

function Estadisticas_menu() {
	
  $items['Estadisticas'] = array(
    'title' => 'Estadisticas',
    'page callback' => 'Estadisticas_main',
    'access arguments' => array('Estadisticas/'),
    'access callback' => TRUE,
    'weight' => 9,
    'menu_name' => 'main-menu',
    'options' => array('attributes' => array('class' => 'Estadisticas_main')),
);
  
   $items['Estadisticas/todas'] = array(
    'title' => 'Estadisticas de las revisiones.',    
    'page callback' => 'drupal_get_form',
    'page arguments' => array('Estadisticas_solicitudes_form'),
    'access arguments' => array('Estadisticas/todas'),
  );

  
  return $items;
}

function Estadisticas_permission() {
  return array(
    'Estadisticas/' => array(
      'title' => t('Permisos para visualizar las listas de revisiones'),
      'description' => t('Seleccion de usuarios que pueden tener acceso.'),
    ),
    'Estadisticas/todas' => array(
      'title' => t('Permisos para visualizar todas'),
      'description' => t('Seleccion de usuarios que pueden tener acceso.'),
    ),
  );
}

function Estadisticas_main(){
			  return t('<ul style="text-align: justify;">
		  		<li>'.l( t("Estadisticas de las revisiones."),'Estadisticas/todas').'</li>
		    	</ul>');		  
}



function Estadisticas_solicitudes_form($form, $form_state){
	$path=drupal_get_path('module','Estadisticas');
	drupal_add_js($path.'/sorttable.js',array('type'=>'file','weight'=>1));
	//form para Numero de Revisiones por auditor:
	$res = Estadisticas_query_solicitud();
	$headers1=$res['headers'];
	$raws=$res['raws'];
 	$raws2=array();
	foreach ($raws as $raw) {
		$raws2[$raw['nid']]=$raw;
	}
    $leyenda = '<h3>Numero de revisiones por auditor.</h3>';
    		    
    $form['etapa'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
	 $form['table'] = array(
    '#theme' => 'table',
    '#header' => $headers1,
    '#rows' => $raws2,
    '#empty' => t('No existen auditores'),
	'#attributes' => array( 'class' => array('sortable')),
  	);

	//Grafica de auditores.

	$data = $raws2;
	$options_column = array(
	'fields' => array(
	'auditorias' => array(
	'label' => t('Auditorias'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'auditor',
	),
	'data' => $data,
	'type' => 'pie',
	);

	$form['column'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_column,
	);

/*	//form para Hallazgos por revisiones:
	$res = Estadisticas_query_hallxrev();
	$headers2=$res['headers'];
	$raws=$res['raws'];
 	$raws3=array();
	foreach ($raws as $raw) {
		$raws3[$raw['FID']]=$raw;
	}
    $leyenda = 'Que hallazgos tiene cada sitio.';
    		    
    $form['etapa2'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );

*
	$sitios=db_select('solicitud','t')
  			->fields('t',array('id_solicitud','sitio_nombre'))
			->orderBy('sitio_nombre','ASC')
			->execute()
			->fetchAllKeyed();
    		    
	 $form['sitios'] = array(

    '#title' => t('Sitio la que se desea ver hallazgos.'),
    '#type' => 'select',
    '#options' => $sitios,
    '#required' => TRUE,
    '#empty_option' => '-Seleccione-',
  );

	$form['submit_site'] = array(
      '#value' => 'Generar',
      '#type' => 'submit',
      '#submit' => array('alta_rev_enviar'),
    );	


	 $form['table2'] = array(
    '#theme' => 'table',
    '#header' => $headers2,
    '#rows' => $raws3,
    '#empty' => t('No existen revisiones o hallazgos.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);

	//Grafica para hallazgos por revisiones:
/*
	$data = $raws3;
	$options_column = array(
	'title' => 'Hallazgos por revisiones',
	'fields' => array(
	'' => array(
	'label' => t('Auditorias'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'auditor',
	),
	'data' => $data,
	'type' => 'column',
	);

	$form['column'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_column,
	);
*/

	//form para Numero de Hallazgos totales:
	$res = Estadisticas_query_hall_tot();
	$headers3=$res['headers'];
	$raws=$res['raws'];
 	$raws4=array();
	foreach ($raws as $raw) {
		$raws4[$raw['hallazgo']]=$raw;
	}
    $leyenda = '<h3>Hallazgos más encontrados</h3>';
    		    
    $form['etapa3'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
	 $form['table3'] = array(
    '#theme' => 'table',
    '#header' => $headers3,
    '#rows' => $raws4,
    '#empty' => t('No existen hallazgos.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);


	//Grafica para el Numero de Hallazgos Totales:
	$data = $raws4;
	$options_column = array(
	'fields' => array(
	'num_hallazgos' => array(
	'label' => t('Número de Hallazgos'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'hallazgo',
	),
	'data' => $data,
	'type' => 'bar',
	);

	$form['column2'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_column,
	);



	//form para Numero de Herramientas totales:
	$res = Estadisticas_query_herr_tot();
	$headers4=$res['headers'];
	$raws=$res['raws'];
 	$raws5=array();
	foreach ($raws as $raw) {
		$raws5[$raw['herramienta']]=$raw;
	}
    $leyenda = '<h3>Top de herramientas más utilizadas en revisiones.</h3>';
    		    
    $form['etapa4'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
/*
	 $form['table4'] = array(
    '#type' => 'tableselect',
    '#header' => $headers4,
    '#options' => $raws5,
    '#empty' => t('No existen herramientas.'),
  	);
*/
	 $form['table4'] = array(
    '#theme' => 'table',
    '#header' => $headers4,
    '#rows' => $raws5,
    '#empty' => t('No existen herramientas.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);

	#echo theme('table', array('header'=>$headers4, 'rows'=>$raws5));
/*
	$data = array(
	array('fruit' => 'apple', 'votes' => 16),
	array('fruit' => 'mango', 'votes' => 10),
	array('fruit' => 'banana', 'votes' => 34),
	array('fruit' => 'peach', 'votes' => 20),
	array('fruit' => 'orange', 'votes' => 15),
	);
*/

	$data = $raws5;
	$options_pie = array(
	'fields' => array(
	'usos' => array(
	'label' => t('Usos'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'herramienta',
	),
	'data' => $data,
	'type' => 'pie',
	);

/*

	$options_column = array(
	'title' => 'Favourite fruits',
	'fields' => array(
	'votes' => array(
	'label' => t('Votes'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'fruit',
	),
	'data' => $data,
	'type' => 'column',
	);
*/
	$form['pie'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_pie,
	);
/*
	$form['column'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_column,
	);

*/
/*
	$format = 'Y-m-d';

   $form['fecha_ini'] = array(
    '#title' => t('Fecha de inicio de la revisión:'),
    '#type' => 'date_popup',
    '#required' => TRUE,
    '#date_format' => $format,
    '#date_label_position' => 'within',
    '#filters' => array('trim','strip_tags'),
    '#default_value' => $fecha_ini,
  );
  
   $form['fecha_fin'] = array(
    '#title' => t('Fecha de fin de la revisión:'),
    '#type' => 'date_popup',
    '#required' => TRUE,
    '#date_format' => $format,
    '#date_label_position' => 'within',
    '#filters' => array('trim','strip_tags'),
    '#default_value' => $fecha_fin,
  );
	$form['submit'] = array(
      '#value' => 'Subir',
      '#type' => 'submit',
      '#submit' => array('hallazgosxtiempo'),
    );	

	$fecha_ini=filter_var(strip_tags($form_submit['values']['fecha_ini']),FILTER_SANITIZE_STRING);

	$fecha_fin=filter_var(strip_tags($form_submit['values']['fecha_fin']),FILTER_SANITIZE_STRING);

*/

	//form para Numero de Revisiones por año:
	$res = Estadisticas_query_revxyear();
	$headers6=$res['headers'];
	$raws=$res['raws'];
 	$raws7=array();
	foreach ($raws as $raw) {
		$raws7[$raw['año']]=$raw;
	}
    $leyenda = '<h3>Numero total de revisiones por año.</h3>';
    		    
    $form['etapa6'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
	 $form['table6'] = array(
    '#theme' => 'table',
    '#header' => $headers6,
    '#rows' => $raws7,
    '#empty' => t('No existen revisiones.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);

	//Grafica para el Numero de Revisiones Totales por año:
	$data = $raws7;
	$options_line = array(
	'fields' => array(
	'solicitudes' => array(
	'label' => t('Solicitudes'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'año',
	),
	'data' => $data,
	'type' => 'line',
	);

	$form['line'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_line,
	);


	//form para Numero de Revisiones por año:
	$res = Estadisticas_query_auditxsite();
	$headers7=$res['headers'];
	$raws=$res['raws'];
 	$raws8=array();
	foreach ($raws as $raw) {
		$raws8[$raw['id']]=$raw;
	}
  /*  $leyenda = 'Revisiones realizadas por cada auditor.';
    		    
    $form['etapa7'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
	 $form['table7'] = array(
    '#theme' => 'table',
    '#header' => $headers7,
    '#rows' => $raws8,
    '#empty' => t('No existen revisiones.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);*/
/*
	//Grafica para el Numero de Revisiones Totales por año:
	$data = $raws8;
	$options_line = array(
	'title' => 'Revisiones realizadas por auditor.',
	'fields' => array(
	'solicitudes' => array(
	'label' => t('Solicitudes'),
	'enabled' => TRUE,
	),
	),
	'xAxis' => array(
	'labelField' => 'año',
	),
	'data' => $data,
	'type' => 'line',
	);

	$form['line'] =  array(
	'#theme' => 'visualization',
	'#options' => $options_line,
	);

*/
  return $form;	

}

function hallazgosxtiempo(){
	$form_submit['values']['fecha_ini']=$fecha_ini;
	$form_submit['values']['fecha_fin']=$fecha_fin;
	$fecha_ini=$form_submit['values']['fecha_ini'];
	$fecha_fin=$form_submit['values']['fecha_fin'];

	//form para Hallazgos con mayor repetición por año:
	$res = Estadisticas_query_hallxyear();
	$headers5=$res['headers'];
	$raws=$res['raws'];
 	$raws6=array();
	foreach ($raws as $raw) {
		$raws6[$raw['hallazgo']]=$raw;
	}
    $leyenda = 'Top de hallazgos por año.';
    		    
    $form['etapa5'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );

	 $form['table5'] = array(
    '#theme' => 'table',
    '#header' => $headers5,
    '#rows' => $raws6,
    '#empty' => t('No existen hallazgos.'),
	'#attributes' => array( 'class' => array('sortable')),
  	);
}

function Estadisticas_query_solicitud(){	
	
#	  $registro  = db_query('SELECT nid, title auditor, count(sitio_nombre) auditorias from node,revision,solicitud where type=\'auditor\' and nid_auditor=nid and solicitud.id_solicitud=revision.id_solicitud GROUP BY nid,title;');
$registro = db_query('SELECT n.nid, n.title auditor, count(s.sitio_nombre) auditorias from node n, revision r, solicitud s where type=\'auditor\' and r.nid_auditor=n.nid and s.id_solicitud=r.id_solicitud GROUP BY n.title,n.nid;');
	 
/*
 $registro=db_select('node','n');
$registro->join('revision','r','r.nid_auditor=n.nid');
$registro->join('solicitud','s','s.id_solicitud=r.id_solicitud');
$registro->fields('n',array('nid','title'))
	->condition('n.type','auditor','=')
        ->orderBy('n.nid','ASC');
$registro->addExpression('COUNT(s.sitio_nombre)', 'auditorias');
$registro->execute()
         ->fetchAllKeyed();
*/
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'nid'=>'Identificador','auditor'=>'Auditor','auditorias'=>'Auditorias');
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	$array_tmp["nid"] 				= $valor['nid'];
			$array_tmp["auditor"] 			= $valor['auditor'];
			$array_tmp["auditorias"]	 	= $valor['auditorias'];	
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
}

function Estadisticas_query_hallxrev(){
	
	  $registro  = db_query('SELECT r.id_revision || \'\' || nid_hallazgo FID, sitio_nombre, title hallazgo FROM node n, field_data_field_descripcion_hallazgo dh, hall_rev hr, solicitud s, revision r WHERE entity_id=nid AND nid_hallazgo=nid AND s.id_solicitud=r.id_solicitud AND r.id_revision=hr.id_revision ORDER BY sitio_nombre;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'ID'=>'FID','sitio_nombre'=>'sitio_nombre','hallazgo'=>'hallazgo');
	  $i=0;
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	$array_tmp["FID"] 				= $i;
		  	$array_tmp["sitio_nombre"] 		= $valor['sitio_nombre'];
			$array_tmp["hallazgo"] 			= $valor['hallazgo'];
	    array_push($array['raws'],$array_tmp);
		$i++;
	  }
	  return $array;		
}

function Estadisticas_query_hall_tot(){
	
#	  $registro  = db_query('SELECT nid, title hallazgo, count(title) num_hallazgos FROM node, hall_rev WHERE type=\'hallazgo\' and nid=nid_hallazgo GROUP BY nid ORDER BY num_hallazgos DESC;');
$registro = db_query('SELECT n.nid, n.title hallazgo, count(n.title) num_hallazgos FROM node n, hall_rev hr WHERE type=\'hallazgo\' and n.nid=hr.nid_hallazgo GROUP BY n.nid,n.title ORDER BY num_hallazgos DESC;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'hallazgo'=>'Hallazgo','num_hallazgos'=>'Total en revisiones');
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	#$array_tmp["NID"] 			= $valor['nid'];
		  	$array_tmp["hallazgo"] 		= $valor['hallazgo'];
			$array_tmp["num_hallazgos"]	= $valor['num_hallazgos'];
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
}

function Estadisticas_query_herr_tot(){
	
#	  $registro  = db_query('SELECT nid, title herramienta, count(nid) usos FROM node, rev_herr WHERE type=\'herramienta\' AND nid_herramienta=nid GROUP BY nid ORDER BY usos DESC;');
$registro = $registro  = db_query('SELECT n.nid, n.title herramienta, count(n.nid) usos FROM node n, rev_herr rh WHERE type=\'herramienta\' AND rh.nid_herramienta=n.nid GROUP BY n.nid,n.title ORDER BY usos DESC;');	  

	db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'herramienta'=>'Herramienta','usos'=>'Total en usos');
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  //	$array_tmp["NID"] 			= $valor['nid'];
		  	$array_tmp["herramienta"] 	= $valor['herramienta'];
			$array_tmp["usos"]			= $valor['usos'];
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
}

function Estadisticas_query_hallxyear(){
	
	  $registro  = db_query(' SELECT nid, title hallazgo, count(title) num_hallazgos FROM node, hall_rev, solicitud, revision WHERE type=\'hallazgo\' and nid=nid_hallazgo AND fecha_sol >='.$fecha_ini.' AND fecha_sol<='.$fecha_sol.' AND solicitud.id_solicitud=revision.id_solicitud AND hall_rev.id_revision=revision.id_revision GROUP BY nid ORDER BY num_hallazgos DESC;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'hallazgo'=>'hallazgo','num_hallazgos'=>'num_hallazgos');
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	#$array_tmp["NID"] 			= $valor['nid'];
		  	$array_tmp["hallazgo"] 	= $valor['hallazgo'];
			$array_tmp["num_hallazgos"]	= $valor['num_hallazgos'];
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
}

function Estadisticas_query_revxyear(){
	
	  $registro  = db_query('SELECT EXTRACT(YEAR FROM fecha_ini) año, count(id_solicitud) solicitudes FROM solicitud WHERE num_rev > 1 GROUP BY año ORDER BY año;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'año'=>'Año','solicitudes'=>'Total de revisiones');
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
			$array_tmp["año"]	= $valor['año'];
		  	$array_tmp["solicitudes"] 	= $valor['solicitudes'];
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
}

function Estadisticas_query_auditxsite(){
	
	  $registro  = db_query('SELECT s.id_solicitud, title auditor, sitio_nombre nombre_sitio, fecha_ini fecha, CASE WHEN estado_rev=1 THEN \'Solicitud\' WHEN estado_rev=2 THEN \'Revision Inicial\' WHEN estado_rev=3 THEN \'Primera Revisión de Seguimiento\' WHEN estado_rev=4 THEN \'Segunda Revisión de Seguimiento\' ELSE \'Revisión Extraordinaria de Seguimiento\' END Estado from node n, solicitud s, revision r WHERE s.id_solicitud=r.id_solicitud AND nid_auditor=nid order by title;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'id'=>'ID','auditor'=>'Auditor Responsable','nombre_sitio'=>'Nombre del sitio','fecha'=>'Fecha','estado'=>'Estado');
	  $i=0;
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	$array_tmp["id"] = $i;
			$array_tmp["auditor"]	= $valor['auditor'];
			$array_tmp["nombre_sitio"]	= $valor['nombre_sitio'];
		  	$array_tmp["fecha"] 	= $valor['fecha'];
			$array_tmp["estado"] 	= $valor['estado'];
	    	array_push($array['raws'],$array_tmp);
			$i++;
	  }
	  return $array;		
}
