(function ($){                                                                                                                                                                                                                                                      
  jQuery(document).ready(function ($) {		
  	
  	if (!(/Generar/.test(window.location.href))){return;}
                                                                                                                                                                                                                                                       
    $('#edit-hallazgo-1').click(function(event) {                                                                                                                                                                                                                        
      if(this.checked) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  	  	for(index = 2; index < 100; index++){                                                                                                                                                                                                           
  	  	  var id = "#edit-hallazgo-";                                                                                                                                                                                                                                      
  	  	  id = id.concat(index);                                                                                                                                                                                                                          
  	  	  $(id).attr("disabled", "disabled");                                                                                                                                                                                                                            
  	  	}                                                                                                                                                                                                                 
      }else{                                                                                                                                                                                                                                                        
        for(index = 2; index < 100; index++){                                                                                                                                                                                                           
  	  	  var id = "#edit-hallazgo-";                                                                                                                                                                                                                                      
  	  	  id = id.concat(index);                                                                                                                                                                                                                          
  	  	  $(id).removeAttr("disabled");                                                                                                                                                                                                                          
  	  	}      	                                                                                                                                                                                                            
     }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    });
	

	
	$('#edit-hallazgo-48, #edit-hallazgo-51, #edit-hallazgo-53').click(function(event) {                                                                                                                                                                                                                        
      if(this.checked) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  	  	                                                                                                                                                                                                                         
  	  	  $('#edit-hallazgo-1').attr("disabled", "disabled");                                                                                                                                                                                                                            
                                                                                                                                                                                                             
      }else{ 
      	
      	 if($('#edit-hallazgo-48').is(":checked") || $('#edit-hallazgo-51').is(":checked") || $('#edit-hallazgo-53').is(":checked")){                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  	  	   $('#edit-hallazgo-1').attr("disabled", "disabled"); 
  	  	  } 
  	  	  else{
  	  	  $('#edit-hallazgo-1').removeAttr("disabled"); 
  	  	  }                                                                                                                                                                                                                    	                                                                                                                                                                                                            
     }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
});
})(jQuery);                                                                                                                                                                                                                                                         