<?php
/*
*Form Listado de revisión
*@author: mvasquez & varteaga
*@date: 29/09/2015
*/

function Lista_menu() {
	
  $items['Lista'] = array(
    'title' => 'Lista',
    'page callback' => 'Lista_main',
    'access arguments' => array('Lista/'),
    'access callback' => TRUE,
    'weight' => 9,
    'menu_name' => 'main-menu',
    'options' => array('attributes' => array('class' => 'Lista_main')),
);
  
   $items['Lista/todas'] = array(
    'title' => 'Todas las solicitudes.',    
	'page callback' => 'drupal_get_form',
    'page arguments' => array('Lista_solicitudes_form'),
    'access arguments' => array('Lista/todas'),
  );

  
  return $items;
}

function Lista_permission() {
  return array(
    'Lista/' => array(
      'title' => t('Permisos para visualizar las listas de revisiones'),
      'description' => t('Seleccion de usuarios que pueden tener acceso.'),
    ),
  );
}

function Lista_main(){
			  return t('<ul style="text-align: justify;">
		  		<li>'.l( t("Listado de todas las solicitudes."),'Lista/todas').'</li>
		    	</ul>');		  
}



function Lista_solicitudes_form($form, $form_state){
	
	$res = Lista_query_solicitud();
	$headers=$res['headers'];
	$raws=$res['raws'];
 	$raws2=array();
	foreach ($raws as $raw) {
		$raws2[$raw['ID']]=$raw;
	}
    $leyenda = Lista_main();
    		    
    $form['etapa'] = array(
      '#type' => 'item',
      '#title' => $leyenda,
    );
	 $form['table'] = array(
    '#type' => 'tableselect',
    '#header' => $headers,
    '#options' => $raws2,
    '#empty' => t('No existen solicitudes'),
    '#multiple' => FALSE,
  	);
	
	$form['submit'] = array(
      '#value' => 'Generar documento',
      '#type' => 'submit',
      '#submit' => array('Lista_generar'),
    );
  return $form;	
}

function Lista_query_solicitud(){
	
	  $registro = db_query('SELECT s.id_solicitud, uw.url_link, s.fecha_ini, s.fecha_fin FROM solicitud s, sitio_web sitw, url_web uw where s.id_sitweb = sitw.id_sitweb and sitw.id_sitweb = uw.id_sitweb;');
	  db_set_active('default');
  
	  $res = array();
	  
      foreach ($registro as $valor) {
	    array_push($res,get_object_vars($valor));
  	  }	
   	  
	  $array = array();
	  $array['raws'] =array();
	  $array['headers'] =array( 'ID'=>'ID','URL_Sitio'=>'URL_Sitio','Fecha_Inicio'=>'Fecha_Inicio','Fecha_Fin'=>"Fecha_Fin");
	  
	  foreach ($res as $valor) {  
	  	$array_tmp = array();
		  	$array_tmp["ID"] 				= $valor['id_solicitud'];
			$array_tmp["URL_Sitio"] 		= $valor['url_link'];
			$array_tmp["Fecha_Inicio"]	 	= $valor['fecha_ini'];	
			$array_tmp["Fecha_Fin"] 		= $valor['fecha_fin'];
	    array_push($array['raws'],$array_tmp);
	  }
	  return $array;		
	
}
function Lista_generar($form, &$form_submit) {
}

function Lista_genera_xls($html,$filename){

      drupal_add_http_header('Content-Type', 'application/vnd.ms-excel; charset=UTF-8');
	  drupal_add_http_header('Content-Disposition', 'attachment; filename = '.$filename.' .xls');
	 
	  // Instead of writing to a file, we write to the output stream.
	  $fh = fopen('php://output', 'w');
	 
	  // Add a header row
	  fputs($fh, $html);
	 
	  // Close the output stream.
	  fclose($fh);
		
	return ;
}