 CREATE TABLE solicitud (
id_solicitud serial PRIMARY KEY,
nom_org	varchar(80),
tipo_org varchar(40),
fecha_sol date,
fecha_disp date,
fecha_ini date,
fecha_fin date,
nom_adm varchar(50),
correo_admn varchar(60),
tel_adm  varchar(25),
nom_tec varchar(50),
correo_tec varchar(60),
tel_tec  varchar(25),
sist_op varchar(40),
sist_op_ver varchar(100),
ip_sitio varchar(100),
prot_acc_rem varchar(10),
puer_acc_rem varchar(7),
dir_usua varchar(50),
ip_web varchar(15),
puer_acc_web varchar(30),
url_sitio varchar(150),
soft_web varchar(30),
ver_web varchar(10),
ip_bd varchar(15),
puer_acc_bd varchar(20),
nom_bd varchar(30),
soft_bd varchar(20),
ver_bd varchar(5),
estado_rev varchar(15)
);
